Welcome to Mid term Exam on Computer Vision.
In this Exam you will get a chance to understand and work on some of the commonly used functionalities of several inbuilt libraries

Instructions
Use Python 3.x to run this notebook
Write your code only in between the lines 'YOUR CODE STARTS HERE' and 'YOUR CODE ENDS HERE'.
Look up the documentation for each of the Python and Numpy function used.
This Exam is just to make you understand several commonly used library functions.
This is evaluated and award 20 marks

In [ ]:
#import the required Libraries
import numpy as np

**Numpy Basics:**

In [ ]:
# Create a numpy array with size 2*2 with all elements as 8.
import numpy as np
# YOUR CODE STARTS HERE
arr = np.array([[1,2,3,4],[4,5,6,8]])
# YOUR CODE ENDS HERE

In [ ]:
#Find the sum of all the elements, mean, maximum and minimum value of the numpy array defined above

#YOUR CODE STARTS HERE
arr_sum = np.sum(arr)
arr_mean = np.mean(arr)
arr_max = np.max(arr)
arr_min = np.min(arr)
#YOUR CODE ENDS HERE

**Reshaping and Indexing of Numpy Array:**

In [ ]:
#create a 1D numpy array of shape 35 with values 1,2,3..,35

#YOUR CODE STARTS HERE
y = np.shape([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35])
#YOUR CODE ENDS HERE

In [ ]:
# Reshape it as 2D array of shape (5,7)
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35])
print(arr)
y = np.reshape(arr, (5,7))
print(y)
#YOUR CODE STARTS HERE
#y = np.reshape(5,7)
#YOUR CODE ENDS HERE
#y.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]]


In [ ]:
# Extract all the elements from 2nd and 3rd row

#YOUR CODE STARTS HERE
y_row =print(arr[1:3, 1:3])
#YOUR CODE ENDS HERE

IndexError: ignored

In [ ]:
# Extract all the elements from 3rd and 5th and 7th column

#YOUR CODE STARTS HERE
y_column = arr[3,]
print(arr)
y_column = arr[5,]
print(arr)
y_column = arr[5,]
print(arr)
#YOUR CODE ENDS HERE

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [ ]:
#display the created Array as image
#YOUR CODE STARTS HERE
from PIL import Image

w, h = 512, 512
data = np.zeros((h, w, 3), dtype=np.uint8)
data[0:256, 0:256] = [255, 0, 0] # red patch in upper left
img = Image.fromarray(data, 'RGB')
img.save('my.png')
img.show()
#YOUR CODE ENDS HERE

**Reading an image**

In [ ]:
#Read your image both by passing URL and direct passing the image name
import urllib
import urllib.request
from PIL import Image
urllib.request.urlretrieve("https://i.imgur.com/ExdKOOz.png", "sample.png")
img = Image.open("sample.png")
img.show()

**Width, height and color channels**

In [ ]:
#Get the shape of the image and display it as  " Widht : Height: Color channels:"
import cv2

im = cv2.imread('data/src/lena.jpg')

print(type(im))
# <class 'numpy.ndarray'>

print(im.shape)
print(type(im.shape))
# (225, 400, 3)
# <class 'tuple'>

<class 'NoneType'>


AttributeError: ignored

**Show image**

In [ ]:
#display the image using matplot and opencv

**Turning into gray**

In [ ]:
#display the image in grayscale

**Resizing**

In [ ]:
#Resize the image to 120,80 



# display the  resultant image

**Cropping**

In [ ]:
#crop the image to the dimensions:400:1200, 50:1550 


# display the cropped image

**Rotation**

In [ ]:
#Rotate the image to the angle of 55 and by using center of the image as Rotation point


# display the rotated image 

**Blurring an Image**

In [ ]:
#blur the image  by using kernel size



#Display the blurred image

**Finding contours of an image**

In [ ]:
#Find the contours of the cropped image


#Display the resultant image

**Placing one image on top of another**

In [ ]:
#Place one image on another image using mask


#Display the resultant image

**Drawing circles**

In [ ]:
#Draw circles on the specified region of your image


#Display the resultant image

**Drawing Text**

In [ ]:
#Include the Text in your image



# Display the resultant image